cleanup

diff --git a/assume-role-okta b/assume-role-okta
--- a/assume-role-okta
+++ b/assume-role-okta
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-export user_clean=$(cat ~/.okta_aws_login_config | grep okta_username | awk '{ print $3; }')
-
 # START USAGE DOCUMENTATION
 # assume-role-okta is a command line tool to help assume roles through a bastion account.
 # Store your bastion account credentials here ~/.aws/credentials
@@ -22,18 +20,125 @@ YELLOW='\033[0;33m'
 GREEN='\033[0;32m'
 NC='\033[0m' # No Color
 
-echo_out() {
-  if [ -z "$silent" ]; then
-    # If this is outputting to an eval statement we need to output a "echo" as well
-    if [ -z "$OUTPUT_TO_EVAL" ]; then
-      echo "$@"
-    else
-      echo "echo \"$*\";"
-    fi
-  fi
-}
-
 assume-role-okta(){
+
+  #######
+  # FUNCTIONS
+  #######
+  sts_assume(){
+    ROLE_SESSION_ARGS=(--role-arn "${role_arn}")
+    ROLE_SESSION_ARGS+=(--profile "${source_profile_config}")
+    ROLE_SESSION_ARGS+=(--duration-seconds "${ROLE_SESSION_TIMEOUT}")
+    ROLE_SESSION_ARGS+=(--role-session-name "${user_clean}")
+    ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" --output json || echo "fail")
+  }
+
+  oktasume(){
+    full_output=($(okta-aws-cli -e -b -z | cut -d "=" -f2 ))
+    
+    export AWS_ACCESS_KEY_ID=${full_output[1]}
+    export AWS_SECRET_ACCESS_KEY=${full_output[2]}
+    export AWS_SESSION_TOKEN=${full_output[3]}
+    export AWS_SECURITY_TOKEN=${full_output[3]}
+  }
+
+  echo_out() {
+    if [ -z "$silent" ]; then
+      # If this is outputting to an eval statement we need to output a "echo" as well
+      if [ -z "$OUTPUT_TO_EVAL" ]; then
+        echo "$@"
+      else
+        echo "echo \"$*\";"
+      fi
+    fi
+  }
+
+  set_eks(){
+    eks_clusters=$(aws eks list-clusters --query 'clusters[*]' --output text)
+    cluster_array=($(echo $eks_clusters | tr "\t" "\n"))
+
+    if [ ${#cluster_array[@]} -eq 1 ]; then
+      echo_out "󱃾 Switch to $eks_clusters"
+      export KUBECONFIG="$HOME/.kube/$AWS_ACCOUNT_ID-$eks_clusters"
+      aws eks update-kubeconfig --name $eks_clusters --alias $eks_clusters
+      chmod 0600 $KUBECONFIG
+    elif [ ${#cluster_array[@]} -gt 1 ]; then
+      echo_out "More than one EKS Cluster found. Select:"
+      eks_menu "${#cluster_array[@]}" "${cluster_array[@]}"
+    else
+      echo_out "No EKS Cluster found. ignoring ..."
+    fi
+  }
+
+  eks_menu (){
+    arrsize=$1
+    # echo "Size of array: $arrsize"
+    # echo_out "${@:2}"
+    select option in "${@:2}"; do
+      if [ "$REPLY" -gt "$arrsize" ];
+      then
+        echo_out "Exiting..."
+        break;
+      elif [ 1 -le "$REPLY" ] && [ "$REPLY" -le $((arrsize)) ];
+      then
+        # echo "You selected $option which is option $REPLY"
+        echo_out "󰠳 Switch to $option"
+        export KUBECONFIG="$HOME/.kube/$AWS_ACCOUNT_ID-$option"
+        aws eks update-kubeconfig --name $option --alias $option
+        chmod 0600 $KUBECONFIG
+        break;
+      else
+        echo_out "Incorrect Input: Select a number 1-$arrsize"
+      fi
+    done
+  }
+
+  export_variables(){
+    export AWS_ACCESS_KEY_ID=$(echo "$ROLE_SESSION" | jq -r .Credentials.AccessKeyId)
+    export AWS_SECRET_ACCESS_KEY=$(echo "$ROLE_SESSION" | jq -r .Credentials.SecretAccessKey)
+    export AWS_SESSION_TOKEN=$(echo "$ROLE_SESSION" | jq -r .Credentials.SessionToken)
+    export AWS_SESSION_END=$(echo "$ROLE_SESSION" | jq -r .Credentials.Expiration)
+    export AWS_SECURITY_TOKEN=$AWS_SESSION_TOKEN
+    export AWS_ACCOUNT_ID="$account_id"
+    export AWS_ACCOUNT_NAME="$account_name"
+    export AWS_ACCOUNT_ROLE="$role"
+    export GEO_ENV="$account_name" # For GeoEngineer https://github.com/coinbase/geoengineer
+    export AWS_STS_ROLE_ARN="$role_arn"
+    # echo_out "Success! IAM session envars are exported."
+    echo "${GREEN}󱇲 switched role${NC}"
+  }
+
+  set_region(){
+    AWS_CONFIG_REGION="$(aws configure get region --profile ${account_name})"
+    if [ -z  "$AWS_CONFIG_REGION" ]; then
+      AWS_CONFIG_REGION="$(aws configure get region --profile ${default_profile})"
+    fi
+    if [ -z "$aws_region_input" ] && [ -z "$AWS_REGION" ] && [ -z "$AWS_DEFAULT_REGION" ] && [ -z "$AWS_CONFIG_REGION" ] && [ -z "$OUTPUT_TO_EVAL" ]; then
+      echo -n "Assume Into Region [us-east-1]: "
+      read -r region
+      region=${region:-"us-east-1"}
+    elif [ ! -z "$aws_region_input" ]; then
+      # if there is a $aws_region_input then set to $aws_region_input
+      echo_out "Region from parameter $aws_region_input"
+      region="$aws_region_input"
+    elif [ ! -z "$AWS_CONFIG_REGION" ]; then
+      echo_out "Region from config $AWS_CONFIG_REGION"
+      region=$AWS_CONFIG_REGION
+    elif [ ! -z "$AWS_REGION" ]; then
+      # if there is a $AWS_REGION then set to $AWS_REGION
+      region="$AWS_REGION"
+    elif [ ! -z "$AWS_DEFAULT_REGION" ]; then
+      # if there is a $AWS_DEFAULT_REGION then set to $AWS_DEFAULT_REGION
+      region="$AWS_DEFAULT_REGION"
+    fi
+    if [ -z "$region" ]; then
+      echo_out "region not defined"
+      return
+    fi
+    export AWS_REGION="$region"
+    export AWS_DEFAULT_REGION="$region"
+  }
+
 
   #######
   # PRE-CONDITIONS
@@ -137,6 +242,7 @@ EOF
   ROLE_SESSION_TIMEOUT=3600
   DEFAULT_ACCOUNT="default"
   DEFAULT_ROLE="read"
+  user_clean=$USER
 
   if [ -z  "$AWS_PAGER" ]; then
     export AWS_PAGER="cat"
@@ -186,7 +292,7 @@ EOF
         echo_out "Account-ID not found"
       fi
     fi
-   # echo_out $role_input, $account_id
+    # echo_out $role_input, $account_id
   fi
 
   # Validate Account ID
@@ -212,42 +318,9 @@ EOF
   fi
 
   # set region
-  AWS_CONFIG_REGION="$(aws configure get region --profile ${account_name})"
-  if [ -z  "$AWS_CONFIG_REGION" ]; then
-    AWS_CONFIG_REGION="$(aws configure get region --profile ${default_profile})"
-  fi
+  set_region
 
-  if [ -z "$aws_region_input" ] && [ -z "$AWS_REGION" ] && [ -z "$AWS_DEFAULT_REGION" ] && [ -z "$AWS_CONFIG_REGION" ] && [ -z "$OUTPUT_TO_EVAL" ]; then
-    echo -n "Assume Into Region [us-east-1]: "
-    read -r region
-    region=${region:-"us-east-1"}
-  elif [ ! -z "$aws_region_input" ]; then
-    # if there is a $aws_region_input then set to $aws_region_input
-    echo_out "Region from parameter $aws_region_input"
-    region="$aws_region_input"
-  elif [ ! -z "$AWS_CONFIG_REGION" ]; then
-    echo_out "Region from config $AWS_CONFIG_REGION"
-    region=$AWS_CONFIG_REGION
-  elif [ ! -z "$AWS_REGION" ]; then
-    # if there is a $AWS_REGION then set to $AWS_REGION
-    region="$AWS_REGION"
-  elif [ ! -z "$AWS_DEFAULT_REGION" ]; then
-    # if there is a $AWS_DEFAULT_REGION then set to $AWS_DEFAULT_REGION
-    region="$AWS_DEFAULT_REGION"
-  fi
-  if [ -z "$region" ]; then
-    echo_out "region not defined"
-    return
-  fi
-  export AWS_REGION="$region"
-  export AWS_DEFAULT_REGION="$region"
-
-
-  ROLE_SESSION_ARGS=(--role-arn "${role_arn}")
-  ROLE_SESSION_ARGS+=(--profile "${source_profile_config}")
-  ROLE_SESSION_ARGS+=(--duration-seconds "${ROLE_SESSION_TIMEOUT}")
-  ROLE_SESSION_ARGS+=(--role-session-name "${user_clean}")
-  ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" --output json || echo "fail")
+  sts_assume
 
   if [ "$ROLE_SESSION" = "fail" ]; then
     echo_out "${YELLOW}Failed to export session envars.${NC}"
@@ -266,82 +339,20 @@ EOF
       gimme-aws-creds -p $GIMME_AWS_CREDS_CONF_PROFILE
     fi
 
-    ROLE_SESSION_ARGS=(--role-arn "${role_arn}")
-    ROLE_SESSION_ARGS+=(--profile "${source_profile_config}")
-    ROLE_SESSION_ARGS+=(--duration-seconds "${ROLE_SESSION_TIMEOUT}")
-    ROLE_SESSION_ARGS+=(--role-session-name "${user_clean}")
-    ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" --output json || echo "fail")
+    sts_assume
 
     if [ "$ROLE_SESSION" = "fail" ]; then
       echo_out "${RED}Authentication did not work correctly try it manually${NC}"
     else
-      export AWS_ACCESS_KEY_ID=$(echo "$ROLE_SESSION" | jq -r .Credentials.AccessKeyId)
-      export AWS_SECRET_ACCESS_KEY=$(echo "$ROLE_SESSION" | jq -r .Credentials.SecretAccessKey)
-      export AWS_SESSION_TOKEN=$(echo "$ROLE_SESSION" | jq -r .Credentials.SessionToken)
-      export AWS_SESSION_END=$(echo "$ROLE_SESSION" | jq -r .Credentials.Expiration)
-      export AWS_SECURITY_TOKEN=$AWS_SESSION_TOKEN
-      export AWS_ACCOUNT_ID="$account_id"
-      export AWS_ACCOUNT_NAME="$account_name"
-      export AWS_ACCOUNT_ROLE="$role"
-      export GEO_ENV="$account_name" # For GeoEngineer https://github.com/coinbase/geoengineer
-      export AWS_STS_ROLE_ARN="$role_arn"
-      echo "${GREEN}�� switched role${NC}"
+      export_variables
     fi
 
   else
-    export AWS_ACCESS_KEY_ID=$(echo "$ROLE_SESSION" | jq -r .Credentials.AccessKeyId)
-    export AWS_SECRET_ACCESS_KEY=$(echo "$ROLE_SESSION" | jq -r .Credentials.SecretAccessKey)
-    export AWS_SESSION_TOKEN=$(echo "$ROLE_SESSION" | jq -r .Credentials.SessionToken)
-    export AWS_SESSION_END=$(echo "$ROLE_SESSION" | jq -r .Credentials.Expiration)
-    export AWS_SECURITY_TOKEN=$AWS_SESSION_TOKEN
-    export AWS_ACCOUNT_ID="$account_id"
-    export AWS_ACCOUNT_NAME="$account_name"
-    export AWS_ACCOUNT_ROLE="$role"
-    export GEO_ENV="$account_name" # For GeoEngineer https://github.com/coinbase/geoengineer
-    export AWS_STS_ROLE_ARN="$role_arn"
-    # echo_out "Success! IAM session envars are exported."
-    echo "${GREEN}󱇲 switched role${NC}"
+    export_variables
   fi
 
   # Switch to EKS Cluster
-  eks_clusters=$(aws eks list-clusters --query 'clusters[*]' --output text)
-  #count_clusters=$(echo -n "$eks_clusters" | grep -c '^')
-  cluster_array=($(echo $eks_clusters | tr "\t" "\n"))
-
-  eks_menu (){
-    arrsize=$1
-    # echo "Size of array: $arrsize"
-    # echo_out "${@:2}"
-    select option in "${@:2}"; do
-      if [ "$REPLY" -gt "$arrsize" ];
-      then
-        echo_out "Exiting..."
-        break;
-      elif [ 1 -le "$REPLY" ] && [ "$REPLY" -le $((arrsize)) ];
-      then
-        # echo "You selected $option which is option $REPLY"
-        echo_out "󰠳 Switch to $option"
-        export KUBECONFIG="$HOME/.kube/$AWS_ACCOUNT_ID-$option"
-        aws eks update-kubeconfig --name $option --alias $option
-        chmod 0600 $KUBECONFIG
-        break;
-      else
-        echo_out "Incorrect Input: Select a number 1-$arrsize"
-      fi
-    done
-  }
-
-  if [ ${#cluster_array[@]} -eq 1 ]; then
-    echo_out "󱃾 Switch to $eks_clusters"
-    export KUBECONFIG="$HOME/.kube/$AWS_ACCOUNT_ID-$eks_clusters"
-    aws eks update-kubeconfig --name $eks_clusters --alias $eks_clusters
-    chmod 0600 $KUBECONFIG
-  elif [ ${#cluster_array[@]} -gt 1 ]; then
-    echo_out "More than one EKS Cluster found. Select:"
-    eks_menu "${#cluster_array[@]}" "${cluster_array[@]}"
-  else
-    echo_out "No EKS Cluster found. ignoring ..."
-  fi
+  set_eks
 
   # OUTPUTS ALL THE EXPORTS for eval $(assume-role-okta [args])
   if [ "$OUTPUT_TO_EVAL" = "true" ]; then
@@ -377,16 +388,10 @@ EOF
     echo "AWS_PROFILE_ASSUME_ROLE=\"$AWS_PROFILE_ASSUME_ROLE\";"
     echo "AWS_STS_ROLE_ARN=\"$role_arn\";"
   fi
+
 }
 
-oktasume(){
-  full_output=($(okta-aws-cli -e -b -z | cut -d "=" -f2 ))
-  
-  export AWS_ACCESS_KEY_ID=${full_output[1]}
-  export AWS_SECRET_ACCESS_KEY=${full_output[2]}
-  export AWS_SESSION_TOKEN=${full_output[3]}
-  export AWS_SECURITY_TOKEN=${full_output[3]}
-}
+
 
 # from https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
 if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
