updated commands to specify the output format

diff --git a/assume-role b/assume-role
--- a/assume-role
+++ b/assume-role
@@ -120,8 +120,8 @@ assume-role(){
 
     if [ -z "$role_input" ] || [ "$role_input" != '' ]; then
       account_id=`cat $CONF_FILE | sed -n "/^\[profile $account_name\]/,/^\[.*\]/p" | grep "role_arn" | awk '{ print $3 }' | awk -F':' '{ print $5 }'`
-      role_arn=`cat $CONF_FILE | sed -n "/^\[profile $account_name\]/,/^\[.*\]/p" | grep "role_arn" | awk '{ print $3 }'`
-      mfa_serial=`cat $CONF_FILE | sed -n "/^\[profile $account_name\]/,/^\[.*\]/p" | grep "mfa_serial" | awk '{ print $3 }'`
+      role_arn=`aws configure get role_arn --profile $account_name`
+      mfa_serial=`aws configure get mfa_serial --profile $account_name`
     else
       account_id="$account_name_input"
       echo "Using Input as Account-ID instead of name"
@@ -140,6 +140,7 @@ assume-role(){
   if [ -z "$account_id" ]; then
     account_id=$account_name
   fi
+
   # Validate Account ID
   if [[ ! $account_id =~ ^[0-9]{12}$ ]]; then
     echo_out "account_id \"$account_id\" is incorrectly formatted AWS account id"
@@ -224,7 +225,7 @@ assume-role(){
       MFA_DEVICE_ARGS+=(--query 'MFADevices[0].SerialNumber')
       MFA_DEVICE_ARGS+=(--output text)
       MFA_DEVICE_ARGS+=(--profile "${default_profile}")
-      MFA_DEVICE=$(aws iam list-mfa-devices "${MFA_DEVICE_ARGS[@]}")
+      MFA_DEVICE=$(aws iam list-mfa-devices "${MFA_DEVICE_ARGS[@]}" --output json)
       MFA_DEVICE_STATUS=$?
 
       if [ $MFA_DEVICE_STATUS -ne 0 ]; then
@@ -244,7 +245,7 @@ assume-role(){
       SESSION_ARGS+=(--token-code "${mfa_token}")
       SESSION_ARGS+=(--profile "${default_profile}")
 
-      SESSION=$(aws sts get-session-token "${SESSION_ARGS[@]}")
+      SESSION=$(aws sts get-session-token "${SESSION_ARGS[@]}" --output json)
       SESSION_STATUS=$?
 
       if [ $SESSION_STATUS -ne 0 ]; then
@@ -283,7 +284,7 @@ assume-role(){
     ROLE_SESSION_ARGS+=(--token-code "${mfa_token}")
   fi
 
-  ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" || echo "fail")
+  ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" --output json || echo "fail")
 
   if [ "$ROLE_SESSION" = "fail" ]; then
      echo_out "Failed to export session envars."
