option for okta-aws-cli instead of gimme-aws-creds

diff --git a/assume-role-okta b/assume-role-okta
--- a/assume-role-okta
+++ b/assume-role-okta
@@ -34,6 +34,36 @@ echo_out() {
 }
 
 assume-role-okta(){
+
+  #######
+  # PRE-CONDITIONS
+  #######
+
+  # requires authentication tool
+  if [ "ASSUME_TOOL" = "okta-aws-cli" ]; then
+    if ! hash okta-aws-cli 2>/dev/null; then
+      echo_out "assume-role requires 'okta-aws-cli' to be installed"
+      return
+    fi
+  else
+    if ! hash gimme-aws-creds 2>/dev/null; then
+      echo_out "assume-role requires 'gimme-aws-creds' to be installed"
+      return
+    fi
+  fi
+
+  # requires jq
+  if ! hash jq 2>/dev/null; then
+    echo_out "assume-role requires 'jq' to be installed"
+    return
+  fi
+
+  # requires aws
+  if ! hash aws 2>/dev/null; then
+    echo_out "assume-role requires 'aws' to be installed"
+    return
+  fi
+
   # exports
   export AWS_SESSION_START
   export AWS_SESSION_ACCESS_KEY_ID
@@ -77,7 +107,7 @@ EOF
         echo "$HELP"
         exit 1
         ;;
-     \?)
+      \?)
         invalid_options+=($OPTARG)
         ;;
      *)
@@ -220,35 +250,43 @@ EOF
   ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" --output json || echo "fail")
 
   if [ "$ROLE_SESSION" = "fail" ]; then
-     echo_out "${YELLOW}Failed to export session envars. Executing gimme-aws-creds${NC}"
-	  if [ ! -z "$YUBIKEY_OKTA_KEY" ]; then
+    echo_out "${YELLOW}Failed to export session envars.${NC}"
+    if [ ! -z "$YUBIKEY_OKTA_KEY" ]; then
       OKTA_MFA_CODE=$(ykman oath accounts code "$YUBIKEY_OKTA_KEY" | awk '{print $NF}')
       echo_out "Using MFA-Key $YUBIKEY_MFA"
 		export OKTA_MFA_CODE
-	  fi
-     gimme-aws-creds 
+    fi
+    
+    if [ "$ASSUME_TOOL" = "okta-aws-cli" ]; then
+      echo_out "${YELLOW}Executing okta-aws-cli${NC}"
+      oktasume
+    else
+      echo_out "${YELLOW}Executing gimme-aws-creds${NC}"
+      if [ -z $GIMME_AWS_CREDS_CONF_PROFILE ]; then GIMME_AWS_CREDS_CONF_PROFILE="DEFAULT"; fi
+      gimme-aws-creds -p $GIMME_AWS_CREDS_CONF_PROFILE
+    fi
 
-     ROLE_SESSION_ARGS=(--role-arn "${role_arn}")
-	  ROLE_SESSION_ARGS+=(--profile "${source_profile_config}")
-	  ROLE_SESSION_ARGS+=(--duration-seconds "${ROLE_SESSION_TIMEOUT}")
-	  ROLE_SESSION_ARGS+=(--role-session-name "${user_clean}")
-	  ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" --output json || echo "fail")
-     
-	  if [ "$ROLE_SESSION" = "fail" ]; then
-	  	echo_out "${RED}gimme-aws-creds did not work correctly try it manually${NC}"
-	  else
-	  	export AWS_ACCESS_KEY_ID=$(echo "$ROLE_SESSION" | jq -r .Credentials.AccessKeyId)
+    ROLE_SESSION_ARGS=(--role-arn "${role_arn}")
+    ROLE_SESSION_ARGS+=(--profile "${source_profile_config}")
+    ROLE_SESSION_ARGS+=(--duration-seconds "${ROLE_SESSION_TIMEOUT}")
+    ROLE_SESSION_ARGS+=(--role-session-name "${user_clean}")
+    ROLE_SESSION=$(aws sts assume-role "${ROLE_SESSION_ARGS[@]}" --output json || echo "fail")
+
+    if [ "$ROLE_SESSION" = "fail" ]; then
+      echo_out "${RED}Authentication did not work correctly try it manually${NC}"
+    else
+      export AWS_ACCESS_KEY_ID=$(echo "$ROLE_SESSION" | jq -r .Credentials.AccessKeyId)
       export AWS_SECRET_ACCESS_KEY=$(echo "$ROLE_SESSION" | jq -r .Credentials.SecretAccessKey)
-    	export AWS_SESSION_TOKEN=$(echo "$ROLE_SESSION" | jq -r .Credentials.SessionToken)
-    	export AWS_SESSION_END=$(echo "$ROLE_SESSION" | jq -r .Credentials.Expiration)
-    	export AWS_SECURITY_TOKEN=$AWS_SESSION_TOKEN
-    	export AWS_ACCOUNT_ID="$account_id"
-    	export AWS_ACCOUNT_NAME="$account_name"
-    	export AWS_ACCOUNT_ROLE="$role"
-    	export GEO_ENV="$account_name" # For GeoEngineer https://github.com/coinbase/geoengineer
-    	export AWS_STS_ROLE_ARN="$role_arn"
-    	echo "${GREEN}\uf0c2 switched role${NC}"
-	  fi
+      export AWS_SESSION_TOKEN=$(echo "$ROLE_SESSION" | jq -r .Credentials.SessionToken)
+      export AWS_SESSION_END=$(echo "$ROLE_SESSION" | jq -r .Credentials.Expiration)
+      export AWS_SECURITY_TOKEN=$AWS_SESSION_TOKEN
+      export AWS_ACCOUNT_ID="$account_id"
+      export AWS_ACCOUNT_NAME="$account_name"
+      export AWS_ACCOUNT_ROLE="$role"
+      export GEO_ENV="$account_name" # For GeoEngineer https://github.com/coinbase/geoengineer
+      export AWS_STS_ROLE_ARN="$role_arn"
+      echo "${GREEN}�� switched role${NC}"
+    fi
 
   else
     export AWS_ACCESS_KEY_ID=$(echo "$ROLE_SESSION" | jq -r .Credentials.AccessKeyId)
@@ -262,7 +300,7 @@ EOF
     export GEO_ENV="$account_name" # For GeoEngineer https://github.com/coinbase/geoengineer
     export AWS_STS_ROLE_ARN="$role_arn"
     # echo_out "Success! IAM session envars are exported."
-    echo "${GREEN}\uf0c2 switched role${NC}"
+    echo "${GREEN}󱇲 switched role${NC}"
   fi
 
   # Switch to EKS Cluster
@@ -270,8 +308,7 @@ EOF
   #count_clusters=$(echo -n "$eks_clusters" | grep -c '^')
   cluster_array=($(echo $eks_clusters | tr "\t" "\n"))
 
-  eks_menu ()
-  {
+  eks_menu (){
     arrsize=$1
     # echo "Size of array: $arrsize"
     # echo_out "${@:2}"
@@ -295,7 +332,7 @@ EOF
   }
 
   if [ ${#cluster_array[@]} -eq 1 ]; then
-    echo_out "󰠳 Switch to $eks_clusters"
+    echo_out "󱃾 Switch to $eks_clusters"
     export KUBECONFIG="$HOME/.kube/$AWS_ACCOUNT_ID-$eks_clusters"
     aws eks update-kubeconfig --name $eks_clusters --alias $eks_clusters
     chmod 0600 $KUBECONFIG
@@ -340,6 +377,15 @@ EOF
     echo "AWS_PROFILE_ASSUME_ROLE=\"$AWS_PROFILE_ASSUME_ROLE\";"
     echo "AWS_STS_ROLE_ARN=\"$role_arn\";"
   fi
+}
+
+oktasume(){
+  full_output=($(okta-aws-cli -e -b -z | cut -d "=" -f2 ))
+  
+  export AWS_ACCESS_KEY_ID=${full_output[1]}
+  export AWS_SECRET_ACCESS_KEY=${full_output[2]}
+  export AWS_SESSION_TOKEN=${full_output[3]}
+  export AWS_SECURITY_TOKEN=${full_output[3]}
 }
 
 # from https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
