silent and region settable

diff --git a/assume-role b/assume-role
--- a/assume-role
+++ b/assume-role
@@ -17,11 +17,13 @@
 # END USAGE DOCUMENTATION
 
 echo_out() {
-  # If this is outputting to an eval statement we need to output a "echo" as well
-  if [ -z "$OUTPUT_TO_EVAL" ]; then
-    echo "$@"
-  else
-    echo "echo \"$*\";"
+  if [ -z "$silent" ]; then
+    # If this is outputting to an eval statement we need to output a "echo" as well
+    if [ -z "$OUTPUT_TO_EVAL" ]; then
+      echo "$@"
+    else
+      echo "echo \"$*\";"
+    fi
   fi
 }
 
@@ -65,10 +67,57 @@ assume-role(){
   export AWS_PROFILE_ASSUME_ROLE
 
   # INPUTS
+
+  read -r -d '' HELP <<EOF
+  OPTIONS:
+  -s    Enable silent mode
+  -r    Override Region
+  -h    Display this help
+EOF
+
+  OPTIND=1                # Reset in case getopts has been used previously in the shell
+  invalid_options=();     # Array for invalid options
+
+  while getopts ":shr:" opt; do
+    #echo_out "Actual opt: $opt"
+    case $opt in
+      s)
+        silent='true'
+        ;;
+      r)
+        aws_region_input=$OPTARG
+        ;;
+      h)
+        echo "$HELP"
+        exit 1
+        ;;
+     \?)
+        invalid_options+=($OPTARG)
+        ;;
+     *)
+        invalid_options+=($OPTARG)
+        ;;
+    esac
+  done
+
+  # HANDLE INVALID OPTIONS
+  if [ ${#invalid_options[@]} -ne 0 ]; then
+    echo "Invalid option(s):" >&2
+    for i in "${invalid_options[@]}"; do
+      echo $i >&2
+    done
+    echo "" >&2
+    echo "$HELP" >&2
+    exit 1
+  fi
+
+  # SET $1 TO FIRST MASS ARGUMENT, $2 TO SECOND MASS ARGUMENT ETC
+  shift $((OPTIND - 1))
+
+
+
   account_name_input=$1
-  role_input=$2
-  mfa_token_input=$3
-  aws_region_input=$4
+
 
   # DEFAULT VARIABLES
   ACCOUNTS_FILE=${ACCOUNTS_FILE:-~/.aws/accounts}
@@ -90,7 +139,7 @@ assume-role(){
 
   # load default assume-role profile if available, use "default" otherwise
   if [ "$AWS_PROFILE_ASSUME_ROLE" ]; then
-    echo "Using assume-role default profile: $AWS_PROFILE_ASSUME_ROLE"
+    # echo "Using assume-role default profile: $AWS_PROFILE_ASSUME_ROLE"
     default_profile=${AWS_PROFILE_ASSUME_ROLE}
   else
     default_profile="default"
@@ -124,7 +173,7 @@ assume-role(){
       mfa_serial=`aws configure get mfa_serial --profile $account_name`
     else
       account_id="$account_name_input"
-      echo "Using Input as Account-ID instead of name"
+      echo_out "Using Input as Account-ID instead of name"
       role_arn=`cat $CONF_FILE | grep "$account_id" | awk '{print $3 }'`
       role_input=`cat $CONF_FILE | grep "$account_id" | awk '{print $3 }' | awk -F'/' '{ print $2 }'`
     fi
@@ -175,9 +224,10 @@ assume-role(){
     region=${region:-"us-east-1"}
   elif [ ! -z "$aws_region_input" ]; then
     # if there is a $aws_region_input then set to $aws_region_input
+    echo_out "Region from parameter $aws_region_input"
     region="$aws_region_input"
   elif [ ! -z "$AWS_CONFIG_REGION" ]; then
-    #echo_out "Region from config $AWS_CONFIG_REGION"
+    echo_out "Region from config $AWS_CONFIG_REGION"
     region=$AWS_CONFIG_REGION
   elif [ ! -z "$AWS_REGION" ]; then
     # if there is a $AWS_REGION then set to $AWS_REGION
@@ -302,8 +352,8 @@ assume-role(){
     AWS_ACCOUNT_ROLE="$role"
     GEO_ENV="$account_name" # For GeoEngineer https://github.com/coinbase/geoengineer
     AWS_STS_ROLE_ARN="$role_arn"
-    # echo_out "Success! IAM session envars are exported."
-    echo_out "\uf65f switched role"
+    echo_out "Success! IAM session envars are exported."
+    echo "\uf65f switched role"
   fi
 
   # OUTPUTS ALL THE EXPORTS for eval $(assume-role [args])
